import { Stream, StreamViewItem } from './type'
import * as moment from 'moment-timezone'

export const streams: Array<Stream> = [];

streams.push({id:1,streamer:'Vox',title:'ASK ME ANY THING',isStreamer:true,link:'https://www.youtube.com/watch?v=uJtjaurhq-M',isCollab:false,timestamp:1645362000000.,guestId:null})
streams.push({id:2,streamer:'Vox',title:'Overwatch',isStreamer:true,link:'https://www.youtube.com/watch?v=dPbkTvFoZ80',isCollab:true,timestamp:1645372800000.,guestId:null})
streams.push({id:3,streamer:'Vox',title:'Ring Fit',isStreamer:true,link:'https://www.youtube.com/watch?v=Xds474RmCUM',isCollab:false,timestamp:1645448400000.,guestId:null})
streams.push({id:4,streamer:'Vox',title:'SIMS 4',isStreamer:true,link:'https://www.youtube.com/watch?v=XIjMf23Of6Q',isCollab:false,timestamp:1645538400000.,guestId:null})
streams.push({id:5,streamer:'Vox',title:'ZATSUDAN',isStreamer:true,link:'https://www.youtube.com/watch?v=BS-HvJLMWg8',isCollab:false,timestamp:1645621200000.,guestId:null})
streams.push({id:6,streamer:'Vox',title:'The Crooked Man',isStreamer:true,link:'https://www.youtube.com/watch?v=MuFMQwmsYmc',isCollab:false,timestamp:1645707600000.,guestId:null})
streams.push({id:7,streamer:'Vox',title:'SUPA CATCHUP ZATSUDAN',isStreamer:true,link:'https://www.youtube.com/watch?v=gtqy1WNoAvU',isCollab:false,timestamp:1645794000000.,guestId:null})
streams.push({id:8,streamer:'Ike',title:'Propnight',isStreamer:true,link:'https://www.youtube.com/watch?v=BbyIJjJ3Dy4&t=9347s',isCollab:false,timestamp:1645293600000,guestId:null})
streams.push({id:9,streamer:'Ike',title:'Free Chat',isStreamer:true,link:'https://www.youtube.com/watch?v=leFQzQJU0bc',isCollab:false,timestamp:1645358400000,guestId:null})
streams.push({id:10,streamer:'Ike',title:'Free Chat',isStreamer:true,link:'https://www.youtube.com/watch?v=_NNOx0isvJM',isCollab:false,timestamp:1645556400000.,guestId:null})
streams.push({id:11,streamer:'Ike',title:'APEX',isStreamer:true,link:'https://www.youtube.com/watch?v=HE8Ivd-7cEU&t=12344s',isCollab:true,timestamp:1645635600000.,guestId:null})
streams.push({id:12,streamer:'Ike',title:'',isStreamer:false,link:'',isCollab:null,timestamp:null,guestId:6})
streams.push({id:13,streamer:'Ike',title:'',isStreamer:false,link:'',isCollab:null,timestamp:null,guestId:29})
streams.push({id:14,streamer:'Ike',title:'Firewatch',isStreamer:true,link:'https://www.youtube.com/watch?v=DlH1ptG_xck',isCollab:false,timestamp:1645804800000.,guestId:null})
streams.push({id:15,streamer:'Ike',title:'ABZU',isStreamer:true,link:'https://www.youtube.com/watch?v=yfThBKqoKPE',isCollab:false,timestamp:1645880400000.,guestId:null})
streams.push({id:16,streamer:'Ike',title:'',isStreamer:false,link:'',isCollab:null,timestamp:null,guestId:17})
streams.push({id:17,streamer:'Nijisanji Official',title:'EN 5th DEBUT',isStreamer:true,link:'https://www.youtube.com/watch?v=Ensyl_-ftkc',isCollab:false,timestamp:1645927200000.,guestId:null})
streams.push({id:18,streamer:'Vox',title:'',isStreamer:false,link:'',isCollab:null,timestamp:null,guestId:13})
streams.push({id:19,streamer:'Luca',title:'Sekiro',isStreamer:true,link:'https://www.youtube.com/watch?v=fBgMU3ykPHA',isCollab:false,timestamp:1645502400000.,guestId:null})
streams.push({id:20,streamer:'Luca',title:'Metal Cear Rising',isStreamer:true,link:'https://www.youtube.com/watch?v=wnotjU2ndSE',isCollab:false,timestamp:1645588800000.,guestId:null})
streams.push({id:21,streamer:'Luca',title:'Mario & Sonic 2020 Olympic Games',isStreamer:true,link:'https://www.youtube.com/watch?v=G33gS6XfXIY',isCollab:true,timestamp:1645664400000.,guestId:null})
streams.push({id:22,streamer:'Ironmouse',title:'Speak of th Devil',isStreamer:true,link:'https://www.youtube.com/watch?v=ug8mukNdvZc',isCollab:false,timestamp:1645750800000.,guestId:null})
streams.push({id:23,streamer:'Luca',title:'',isStreamer:false,link:'',isCollab:null,timestamp:null,guestId:22})
streams.push({id:24,streamer:'Luca',title:'',isStreamer:false,link:'',isCollab:null,timestamp:null,guestId:13})
streams.push({id:25,streamer:'Luca',title:'Dread Hunger',isStreamer:true,link:'https://www.youtube.com/watch?v=EAnqPLoHObc',isCollab:true,timestamp:1645844400000,guestId:null})
streams.push({id:26,streamer:'Mysta',title:'Overwatch',isStreamer:true,link:'https://www.youtube.com/watch?v=JdEZdT5jBZs',isCollab:true,timestamp:1645372800000.,guestId:null})
streams.push({id:27,streamer:'Mysta',title:'APEX',isStreamer:true,link:'https://www.youtube.com/watch?v=wYf17UqgUX8',isCollab:false,timestamp:1645531200000,guestId:null})
streams.push({id:28,streamer:'Mysta',title:'Doulingo',isStreamer:true,link:'https://www.youtube.com/watch?v=4QFLWfnIu_A',isCollab:false,timestamp:1645617600000,guestId:null})
streams.push({id:29,streamer:'Mysta',title:'Luxiem Collab',isStreamer:true,link:'https://www.youtube.com/watch?v=EZyO08qg11g',isCollab:true,timestamp:1645729200000.,guestId:null})
streams.push({id:30,streamer:'Mysta',title:'Chatting',isStreamer:true,link:'https://www.youtube.com/watch?v=T59BYHE9V68',isCollab:false,timestamp:1645790400000,guestId:null})
streams.push({id:31,streamer:'Mysta',title:'Valorant',isStreamer:true,link:'https://www.youtube.com/watch?v=rQ6g9y4B-YM',isCollab:false,timestamp:1645876800000,guestId:null})
streams.push({id:32,streamer:'Shu',title:'Overwatch',isStreamer:true,link:'https://www.youtube.com/watch?v=LcDRKUxiffs',isCollab:true,timestamp:1645372800000.,guestId:null})
streams.push({id:33,streamer:'Shu',title:'Nun Massacre',isStreamer:true,link:'https://www.youtube.com/watch?v=IrxpwcD2VPs',isCollab:false,timestamp:1645570800000.,guestId:null})
streams.push({id:34,streamer:'Shu',title:'Members only',isStreamer:true,link:'',isCollab:false,timestamp:1645646400000.,guestId:null})
streams.push({id:35,streamer:'Shu',title:'',isStreamer:false,link:'',isCollab:null,timestamp:null,guestId:29})
streams.push({id:36,streamer:'Shu',title:'AMONG AS',isStreamer:true,link:'https://www.youtube.com/watch?v=lJBtjRaXXPk',isCollab:true,timestamp:1645819200000.,guestId:null})
streams.push({id:37,streamer:'Shu',title:'Dread Hunger',isStreamer:true,link:'https://www.youtube.com/watch?v=t4phNqxYC_U',isCollab:true,timestamp:1645844400000,guestId:null})
streams.push({id:38,streamer:'Shu',title:'Pokemon Legends: Arceus',isStreamer:true,link:'',isCollab:false,timestamp:1645992000000.,guestId:null})
streams.push({id:39,streamer:'Luca',title:'Litte nightmare',isStreamer:true,link:'https://www.youtube.com/watch?v=2tO4mOHRa1c',isCollab:false,timestamp:1645945200000.,guestId:null})
streams.push({id:40,streamer:'Fulgur',title:'Intro 2.0 - The Black Sheep',isStreamer:true,link:'',isCollab:false,timestamp:1645970400000.,guestId:null})
streams.push({id:41,streamer:'Fulgur',title:'Cyberpunk 2077 - Corpo Cyborg',isStreamer:true,link:'',isCollab:false,timestamp:1646064000000.,guestId:null})
streams.push({id:42,streamer:'Fulgur',title:'Detroit: Become Human',isStreamer:true,link:'',isCollab:false,timestamp:1646172000000.,guestId:null})
streams.push({id:43,streamer:'Fulgur',title:'Smash Ultimate w/Viewers',isStreamer:true,link:'',isCollab:false,timestamp:1646258400000.,guestId:null})
streams.push({id:44,streamer:'Fulgur',title:'Ghostrunner - They Will Run',isStreamer:true,link:'',isCollab:false,timestamp:1646355600000.,guestId:null})
streams.push({id:45,streamer:'Fulgur',title:'Legatus 505 - Stroytime',isStreamer:true,link:'',isCollab:false,timestamp:1646488800000.,guestId:null})
streams.push({id:46,streamer:'Alban',title:'DEBUT 2.0',isStreamer:true,link:'',isCollab:false,timestamp:1646006400000,guestId:null})
streams.push({id:47,streamer:'Alban',title:'ALBAN Q&A',isStreamer:true,link:'',isCollab:false,timestamp:1646100000000.,guestId:null})
streams.push({id:48,streamer:'Alban',title:'SPLINTER CELL: CHAOS THEORY',isStreamer:true,link:'',isCollab:false,timestamp:1646179200000,guestId:null})
streams.push({id:49,streamer:'Alban',title:'SOMA',isStreamer:true,link:'',isCollab:false,timestamp:1646269200000.,guestId:null})
streams.push({id:50,streamer:'Alban',title:'SPLINTER CELL: CHAOS THEORY',isStreamer:true,link:'',isCollab:false,timestamp:1646352000000,guestId:null})
streams.push({id:51,streamer:'Alban',title:'SC:CT WRAPUP/SOMA',isStreamer:true,link:'',isCollab:false,timestamp:1646445600000.,guestId:null})
streams.push({id:52,streamer:'Alban',title:'NOCTYX COLLAB - READY OR NOT',isStreamer:true,link:'',isCollab:true,timestamp:1646535600000,guestId:null})
streams.push({id:53,streamer:'Uki',title:'DEBUT 2.0',isStreamer:true,link:'',isCollab:false,timestamp:1646013600000.,guestId:null})
streams.push({id:54,streamer:'Uki',title:'Marshmallow Q&A / Dono Reading',isStreamer:true,link:'',isCollab:false,timestamp:1646100000000.,guestId:null})
streams.push({id:55,streamer:'Uki',title:'Unreal Life',isStreamer:true,link:'',isCollab:false,timestamp:1646186400000.,guestId:null})
streams.push({id:56,streamer:'Uki',title:'Subway Midnight',isStreamer:true,link:'',isCollab:false,timestamp:1646269200000.,guestId:null})
streams.push({id:57,streamer:'Uki',title:'Narita Boy',isStreamer:true,link:'',isCollab:false,timestamp:1646359200000.,guestId:null})
streams.push({id:58,streamer:'Uki',title:'First Karaoke Stream!',isStreamer:true,link:'',isCollab:false,timestamp:1646445600000.,guestId:null})
streams.push({id:59,streamer:'Uki',title:'READY OR NOT!',isStreamer:true,link:'',isCollab:false,timestamp:1646532000000.,guestId:null})
streams.push({id:60,streamer:'Sonny',title:'INTRO 2.0/ZATSU',isStreamer:true,link:'',isCollab:false,timestamp:1646017200000,guestId:null})
streams.push({id:61,streamer:'Sonny',title:'ULTRAKILL',isStreamer:true,link:'',isCollab:false,timestamp:1646110800000.,guestId:null})
streams.push({id:62,streamer:'Sonny',title:'METAL GEAR RISING: REVEANGENCE',isStreamer:true,link:'',isCollab:false,timestamp:1646190000000,guestId:null})
streams.push({id:63,streamer:'Sonny',title:'TITANALL 2',isStreamer:true,link:'',isCollab:false,timestamp:1646287200000,guestId:null})
streams.push({id:64,streamer:'Sonny',title:'Touhou Luna Nights',isStreamer:true,link:'',isCollab:false,timestamp:1646384400000,guestId:null})
streams.push({id:65,streamer:'Sonny',title:'Katana Zero',isStreamer:true,link:'',isCollab:false,timestamp:1646470800000,guestId:null})
streams.push({id:66,streamer:'Sonny',title:'Ready or Not',isStreamer:true,link:'',isCollab:true,timestamp:1646535600000,guestId:null})
streams.push({id:67,streamer:'Vox',title:'SIMS - LUXIEM ALTERS',isStreamer:true,link:'',isCollab:false,timestamp:1645974000000,guestId:null})
streams.push({id:68,streamer:'Vox',title:'FANFIC READING',isStreamer:true,link:'',isCollab:false,timestamp:1646056800000.,guestId:null})
streams.push({id:69,streamer:'Vox',title:'FNAF5 SECRET ENDING',isStreamer:true,link:'',isCollab:false,timestamp:1646143200000.,guestId:null})
streams.push({id:70,streamer:'Vox',title:'ZATSUSCAPE',isStreamer:true,link:'',isCollab:false,timestamp:1646233200000,guestId:null})
streams.push({id:71,streamer:'Vox',title:'SPYPARTY vs LUCA',isStreamer:true,link:'',isCollab:true,timestamp:1646316000000.,guestId:null})
streams.push({id:72,streamer:'Vox',title:'AO ONI w/ IKE',isStreamer:true,link:'',isCollab:true,timestamp:1646402400000.,guestId:null})
streams.push({id:73,streamer:'Vox',title:'BINAURAL ASMR',isStreamer:true,link:'',isCollab:false,timestamp:1646492400000,guestId:null})

export function setDisplayValue(item: StreamViewItem, tz: string):void {
  item.displayDate = moment(item.timestamp).tz(tz).format('yyyy-MM-DD')
  item.displayTime = moment(item.timestamp).tz(tz).format('HH:mm')
}
